site_name: Calkulate
site_author: Matthew P. Humphreys
site_description: Total alkalinity from titration data.
site_url: https://calkulate.readthedocs.io/
copyright: Copyright &copy; 2019â€”2020  Matthew P. Humphreys  (GNU GPLv3)

repo_name: mvdh7/calkulate
repo_url: https://github.com/mvdh7/calkulate

nav:
  - Overview: index.md
  - Input data: inputs.md
  - Individual titrations: titrations.md
  - Titration datasets: datasets.md
  - References: references.md
  - Version history: versions.md

theme:
  name: material
  language: en
  palette:
    scheme: slate
    primary: cyan
    accent: deep orange
  font:
    text: Noto Sans
    code: Noto Sans Mono

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
